USE [master]
GO

/****** Object:  Database [CUENTAS_BANCOS]    Script Date: 22/02/2021 17:27:03 ******/
DROP DATABASE [CUENTAS_BANCOS]
GO

/****** Object:  Database [CUENTAS_BANCOS]    Script Date: 22/02/2021 17:27:03 ******/
CREATE DATABASE [CUENTAS_BANCOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CUENTAS_BANCOS', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL11.TEW_SQLEXPRESS\MSSQL\DATA\CUENTAS_BANCOS.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CUENTAS_BANCOS_log', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL11.TEW_SQLEXPRESS\MSSQL\DATA\CUENTAS_BANCOS_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CUENTAS_BANCOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET  MULTI_USER 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CUENTAS_BANCOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CUENTAS_BANCOS] SET  READ_WRITE 
GO

